languageCode: en-us
title: Pulumi - Modern Infrastructure as Code

theme: github.com/pulumi/pulumi-hugo

module:
  imports:
    path: github.com/pulumi/pulumi-hugo
    mounts:
      - source: current/content
        target: content
      - source: current/static
        target: static
      - source: current/layouts
        target: layouts
      - source: current/data
        target: data
      - source: current/assets
        target: assets
      - source: current/archetypes
        target: archetypes

disableKinds:
  - category
  - taxonomyTerm

sectionPagesMenu: main
pygmentsCodeFences: true
pygmentsUseClasses: true

# We always generate the robots.txt file. But based on the environment
# built, it may disallow crawling.
enableRobotsTXT: true

# Enabling Git info allows us to have Hugo automatically set the lastmod date in sitemap
# XML with the date the file was last changed (according to Git).
enableGitInfo: true

# Some of our API docs pages are very large with many shortcodes, which can take
# a while to generate (especially in CI), so we raise the limit from the default
# 10 seconds to avoid timeouts when generating the site.
timeout: 300000

outputFormats:
  rss:
    baseName: rss

# We set the outputs explicitly to just "HTML" as otherwise they default to both
# "HTML" and "RSS", and we only want to generate RSS for the blog section -- not
# all sections/taxonomies. We enable RSS as an output for the blog section alone
# in the front matter of content/blog/_index.md and have a custom RSS template
# in layouts/blog/rss.xml.
outputs:
  home:
    - HTML
  section:
    - HTML

taxonomies:
  author: authors
  tag: tags

permalinks:
  authors: /blog/author/:slug/
  tags: /blog/tag/:slug/

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: "github"
      attribute:
        block: false
        title: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

params:
    canonicalURL: https://www.pulumi.com
    repositoryURL: https://github.com/pulumi/docs
    repositoryBranch: master
    meta_desc: |
        Pulumi's open source infrastructure as code SDK enables you to create, deploy,
        and manage infrastructure on any cloud, using your favorite languages.
