baseURL: https://www.pulumi.com/

theme: github.com/pulumi/pulumi-hugo

module:
  imports:
    path: github.com/pulumi/pulumi-hugo
    mounts:
      - source: next/content
        target: content
      - source: next/static
        target: static
      - source: next/layouts
        target: layouts
      - source: next/data
        target: data
      - source: next/assets
        target: assets
      - source: next/archetypes
        target: archetypes
